version: "3.7"
services:
  nuxt:
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile
    image: nuxt-postcard_generator
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    container_name: postcard_generator-nuxt
    restart: unless-stopped
    ports:
      - "80:3000"
